name: wordle
version: '0.0.1'
dependencies:
  - base
  - ansi-terminal
  - random
  - containers

executables:
  wordle:
    main: Main.hs
    other-modules:
      - Options
      - Paths_wordle

    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
